"""
Generated by ChatGPT
"""

import os
import sys

# When running from a PyInstaller bundle, override DLL search
if getattr(sys, 'frozen', False) and hasattr(sys, '_MEIPASS'):
    keystone_dir = os.path.join(sys._MEIPASS, 'keystone')
    os.add_dll_directory(keystone_dir)

    # Monkey-patch CDLL search logic

    import keystone
    import ctypes
    import platform

    try:
        ctypes.cdll.LoadLibrary(os.path.join(keystone_dir, "keystone.dll"))
    except OSError as e:
        print("ERROR: Failed to load Keystone DLL from MEIPASS:", e)
