"""
Generated by ChatGPT
"""

import os
import sys

# When running from a PyInstaller bundle, override DLL search
if getattr(sys, 'frozen', False) and hasattr(sys, '_MEIPASS'):
    capstone_dir = os.path.join(sys._MEIPASS, 'capstone')
    os.add_dll_directory(os.path.join(capstone_dir, "lib"))

    # Monkey-patch CDLL search logic

    import keystone
    import ctypes
    import platform

    try:
        ctypes.cdll.LoadLibrary(os.path.join(capstone_dir, "lib", "capstone.dll"))
    except OSError as e:
        print("ERROR: Failed to load Keystone DLL from MEIPASS:", e)
